version: '3.8'  # Match the version used in your main docker-compose.yml

services:
  ac-worldserver:
    privileged: true
    environment:
      - AC_UPDATES_ENABLE_DATABASES=1
    volumes:
      # Mount modules from host
      - /mnt/sdb2/wow_config/modules:/azerothcore/modules:rw
      - /mnt/sdb2/wow_config/conf/worldserver.conf:/azerothcore/env/dist/etc/worldserver.conf
      - /mnt/sdb2/wow_config/conf/playerbots.conf:/azerothcore/env/dist/etc/modules/playerbots.conf
      - /mnt/sdb2/wow_config/conf/mod_ahbot.conf:/azerothcore/env/dist/etc/modules/mod_ahbot.conf

  phpmyadmin:
    image: phpmyadmin
    networks:
      - ac-network
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    profiles: []
